service/urls.py
# service/urls.py
from django.urls import path

from . import views

urlpatterns = [
        path('', views.HomePageView.as_view(), name='home'),
        path('difference', views.DifferencePageView, name='difference'),
        ]

svc_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls')),
]

service/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from .validators import validate_service_value

import datetime

class Service(models.Model):
    number = models.PositiveSmallIntegerField(primary_key=True, validators=[validate_service_value])
    occurrences = models.PositiveIntegerField()

    def __str__(self):
        ''' a string representation '''
        output = ('%d => %d' % (self.number, self.occurrences)) 
        return str(output)

    def updateOccurrence(self, findThis, newVal):
        '''
        updates value of occurrences by number
        Args:
            findThis (int): number value
            newVal (int): occurrences new value

        '''
        q = self.objects.get(number=findThis)
        q.occurrences = newVal
        q.save()

    def getSumSq(self, number):
        '''
        sets the response format for square difference
        Args:
            number (int): number value

        Returns:
            dict of response values
        '''
        q = self.objects.get(number=number)
        response = { 
                'datetime': datetime.datetime.utcnow(),
                'value': self.getSumSqDifference(number),
                'number': q.number, 
                'occurrences': q.occurrences 
                }
        return response 

    @staticmethod
    def getSumSqDifference(number):
        '''
        gets the sum square difference 
        Args:
            number (int): number to be evaluated

        Returns:
            int: the sum of square of sum and sum of square of number

        TODO: runtime of this is O(n), maybe use better algorithm or 
        use actual translation of equation to math
        see: https://stackoverflow.com/questions/15593428/function-to-calculate-the-difference-between-sum-of-squares-and-square-of-sums
        resulting in runtime of O(1)
        '''
        total = 0
        sumOfSq = 0
        sqOfSum = 0
        difference = 0

        for i in range(1, number+1):
            total += i
            sumOfSq += i*i
            sqOfSum = total*total
            difference = sqOfSum - sumOfSq

        return difference

    @staticmethod
    def filterint(value):
        '''
        filter values received to 0 if non valid integer (0 < value <= 100)
        Args:
            value (int): number to compute sqSumDifference

        Returns:
            int: actual value or 0 (for invalid input)
        '''
        try:
            myval = int(value)
            if 0 < myval <= 100: 
                return myval
        except ValueError:
            return 0
        return 0

service/views.py
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView
from .models import Service

import json

class HomePageView(ListView):
    model = Service
    template_name = 'home.html'

def DifferencePageView(request):
    model = Service
    number = Service.filterint(request.GET.get('number'))
    if not number:
        error_output = {
            'status': 'error',
        }
        return JsonResponse(error_output, status=400)
    
    try:
        obj = Service.objects.get(number=number)
        Service.updateOccurrence(Service, number, (obj.occurrences+1))
    except Service.DoesNotExist:
        obj = Service(number=number, occurrences=1)
        obj.save()

    output = Service.getSumSq(Service, number)

    #obj = Service.objects.get_or_create(number=number, defaults={'occurrences':1}) also returns True
    
    return JsonResponse(output, status=200)

templates/difference.html
<!--templates/difference.html-->

templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Sum Sq Difference Service - Frontend</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/service.css' %}">
</head>
<!--templates/home.html-->
<body>
    <div class='row' style='padding:15px;'>
        <form action=''>
        <div class='col-md-2 col-md-offset-5'>
            <input class='form-control' id='id_number' name='number' type='text' placeholder='Enter 0 < number <= 100'>
        </div>
        <div class='col-md-2 col-md-offset-5' style='text-align:center;'>
            <input type='submit' class='btn btn-primary' value='Compute' id='id_submit'> 
        </div>
        </form>
    </div>

    <div class='alert alert-danger' id='error_blk' style='display:none;'>
        Invalid input! Please enter a number between 0 and 100
    </div>
    <div class="row" id='success_blk' style='display:none;'>
        <table class='table'>
            <thead class='thead-dark'>
                <tr>
                    <th scope='col'>datetime</th>
                    <th scope='col'>value</th>
                    <th scope='col'>number</th>
                    <th scope='col'>occurrences</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th id='datetime_row'></th>
                    <th id='value_row'></th>
                    <th id='number_row'></th>
                    <th id='occurrences_row'></th>
                </tr>
            </tbody>
        </table>
    </div>

    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
    <script src="{% static 'js/service.js' %}"></script>
</body>
</html>